### ISSUE TITLE
choice of  project_name instead of  campaign_name in notebook spectrogram_generator : why ? 

### ISSUE THREAD

**Issue by cazaudo** [Project-OSmOSE/datarmor-toolkit#53]
we should stick to metadata standards here

**Comment by mathieudpnt** [comment]
yes that is the reason we changed campaign to project ...

**Comment by cazaudo** [comment]
ok so we should remove all occurrences of "campaign" and be consistent with dataset attributes , this is weird : dataset.campaign = project_name

**Comment by Gautzilla** [comment]
`dataset.campaign`: neither `Dataset` nor `Spectrogram` classes have a `campaign` field, so yeah this line doesn't make much sense.

**Comment by cazaudo** [comment]
yes indeed , very weird it does not generate attribute errors! or does it ?

I removed all occurrences of "campaign" and replaced them with "project" on the related branch

**Comment by Gautzilla** [comment]
It doesn't because the attribute is added, not read:

```py
class A:
    def __init__(self, value: int):
        self.value = value

a = A(5)
a.new_attribute = "new attribute" # No exception
print(a.new_attribute)
print(a.unexisting_attribute) # exception
```

You can add an attribute from outside the class without raising an exception. It's just that I don't think the `dataset.campaign` attribute is read anywhere and could thus be removed from the notebook.

**Comment by cazaudo** [comment]
yes indeed thank you for the reminder:)

and @MaelleTtrt has already created a PR https://github.com/Project-OSmOSE/datarmor-toolkit/pull/50 so i close this issue now
